autoscaling:
  enabled: true
  # initialScale: ...
  # maxScale: ...
  # metric: ...
  # minScale: ...
  # scaleDownDelay: ...
  # scaleToZeroPodRetentionPeriod: ...
  # target: ...
bitstreams:
  intel/pac_a10/38d782e3b6125343b9342433e348ac4c: intel/compression/1.0/1gzip
  intel/pac_s10/9346116da52d5ca8b06aa9a389ef7c8d: intel/compression/1.0/2gzip
  intel/pac_s10_usm/9346116da52d5ca8b06aa9a389ef7c8d: intel/compression/1.0/2gzip
env:
  WEB_CONCURRENCY: 1
fpga: 1
image: inaccel/marketplace
# platform: ...
pullPolicy: Always
# pullSecret: ...
tag: gzip
# replicas: ...
