# autoscaling:
#   initialScale: ...
#   maxScale: ...
#   metric: ...
#   minScale: ...
#   scaleDownDelay: ...
#   scaleToZeroPodRetentionPeriod: ...
#   target: ...
# cpu: ...
# credentials:
#   databricks:
#     host: ...
#     insecure: ...
#     password: ...
#     token: ...
#     username: ...
#   mlflow:
#     trackingInsecureTls: ...
#     trackingPassword: ...
#     trackingToken: ...
#     trackingUri: ...
#     trackingUsername: ...
#   s3:
#     accessKeyId: ...
#     region: ...
#     secretAccessKey: ...
image: inaccel/heflow
# key: ...
# memory: ...
# model: ...
# nodeSelector: ...
# pullPolicy: ...
tag: latest
# workers: ...
